-- File generated by the BNF Converter (bnfc 2.9.5).

-- Templates for pattern matching on abstract syntax

{-# OPTIONS_GHC -fno-warn-unused-matches #-}

module SkelLambdaNat where

import Prelude (($), Either(..), String, (++), Show, show)
import qualified AbsLambdaNat

type Err = Either String
type Result = Err String

failure :: Show a => a -> Result
failure x = Left $ "Undefined case: " ++ show x

transId :: AbsLambdaNat.Id -> Result
transId x = case x of
  AbsLambdaNat.Id string -> failure x

transProgram :: AbsLambdaNat.Program -> Result
transProgram x = case x of
  AbsLambdaNat.Prog exps -> failure x

transExp :: AbsLambdaNat.Exp -> Result
transExp x = case x of
  AbsLambdaNat.Abs id exp -> failure x
  AbsLambdaNat.If exp1 exp2 exp3 exp4 -> failure x
  AbsLambdaNat.Let id exp1 exp2 -> failure x
  AbsLambdaNat.Rec id exp1 exp2 -> failure x
  AbsLambdaNat.Fix exp -> failure x
  AbsLambdaNat.Hd exp -> failure x
  AbsLambdaNat.Tl exp -> failure x
  AbsLambdaNat.LE exp1 exp2 -> failure x
  AbsLambdaNat.Plus exp1 exp2 -> failure x
  AbsLambdaNat.Minus exp1 exp2 -> failure x
  AbsLambdaNat.Times exp1 exp2 -> failure x
  AbsLambdaNat.Power exp1 exp2 -> failure x
  AbsLambdaNat.App exp1 exp2 -> failure x
  AbsLambdaNat.Nil -> failure x
  AbsLambdaNat.Cons exp1 exp2 -> failure x
  AbsLambdaNat.Int integer -> failure x
  AbsLambdaNat.Var id -> failure x
